require 'nugator/operation/source/fetch_content'
require 'nugator/operation/source/parse_item'
require 'nugator/operation/source/validate'
require 'nugator/operation/source/construct'
require 'nugator/operation/source/store'
